### ISSUE TITLE
Use Latest Auth Package TestDouble (Remove Duplicate Mocks)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth-mvp#21]
We recently added a [**`TestDouble`**](https://martinfowler.com/bliki/TestDouble.html) to both `elixir-auth-github` and `elixir-auth-google` which makes it _much_ easier for people _using_ those packages to test their code. 🎉 see: https://github.com/dwyl/elixir-auth-google/issues/35 

That means we no longer need to have the files:
+ https://github.com/dwyl/auth-mvp/blob/84f1b76b8903b5467ceb2f3977e1250af077fb20/lib/mock/elixir_auth_github.ex
+ https://github.com/dwyl/auth-mvp/blob/84f1b76b8903b5467ceb2f3977e1250af077fb20/lib/mock/elixir_auth_google.ex

Additionally we will no longer need the following configuration lines in `test.exs`:
https://github.com/dwyl/auth-mvp/blob/f027488eec5ce1d51bb79257f10e343eb936479f/config/test.exs#L19-L20

# Todo

+ [x] Update packages in `mix.exs`
+ [x] Remove config lines from `test.exs`
+ [x] Update Tests if Necessary

**Comment by nelsonic** [comment]
This is done in PR #22 ✅
